export const LABEL_FIELDS = Object.freeze({
  bookLabel: {default:'Our first book',title:'First book label',max:80,group:'Book and illustration'},
  authorPrefix: {default:'by',title:'Before the author name',max:40,group:'Book and illustration'},
  artworkCaption: {default:'Onegin and Tatyana.',title:'Onegin illustration caption',max:300,group:'Book and illustration'},
  artworkCredit: {default:'Elena Samokish-Sudkovskaya, 1908',title:'Onegin illustration credit',max:150,group:'Book and illustration'},
  artworkAlt: {default:'Onegin speaks to Tatyana beside a white bench in a flowering garden.',title:'Onegin illustration description',max:300,group:'Book and illustration'},
  membershipOpens: {default:'Membership opens',title:'Membership opening date label',max:80,group:'Dates and membership'},
  readingStarts: {default:'We start reading',title:'Reading start date label',max:80,group:'Dates and membership'},
  membership: {default:'Membership',title:'Signup price label',max:80,group:'Dates and membership'},
  waitlistCta: {default:'Join the waitlist',title:'Waitlist button',max:70,group:'Dates and membership'},
  patreonCta: {default:'Join on Patreon',title:'Patreon button',max:70,group:'Dates and membership'},
  statusComingSoon: {default:'Coming soon',title:'Coming soon status',max:80,group:'Dates and membership'},
  statusMembershipOpen: {default:'Membership is open',title:'Membership open status',max:80,group:'Dates and membership'},
  statusReading: {default:'Reading together',title:'Reading status',max:80,group:'Dates and membership'},
  homeNav: {default:'Home',title:'Home menu link',max:32,group:'Menu and footer'},
  firstBookNav: {default:"October's Book",title:'First book menu link',max:32,group:'Menu and footer'},
  menuTitle: {default:'Menu',title:'Small-screen menu heading',max:40,group:'Menu and footer'},
  menuOpen: {default:'Open menu',title:'Open menu button',max:80,group:'Menu and footer'},
  menuClose: {default:'Close menu',title:'Close menu button',max:80,group:'Menu and footer'},
  footerMotto: {default:'Read. Think. Question.',title:'Footer motto',max:150,group:'Menu and footer'},
  contact: {default:'Contact Olga Ruchina',title:'Contact link',max:80,group:'Menu and footer'},
  privacy: {default:'Privacy',title:'Privacy link',max:40,group:'Menu and footer'},
  instagramPrefix: {default:'Instagram:',title:'Before the club Instagram handle',max:40,group:'Menu and footer'},
  instagramFallback: {default:'Instagram',title:'Instagram label when no handle is available',max:40,group:'Menu and footer'},
  imageSource: {default:'Image source',title:'Image source link',max:70,group:'Links and accessibility'},
  opensNewTab: {default:'Opens in a new tab',title:'External link hint',max:100,group:'Links and accessibility'},
  skipToContent: {default:'Skip to content',title:'Skip navigation link',max:80,group:'Links and accessibility'},
  pageNavigation: {default:'Main navigation',title:'Main navigation description',max:80,group:'Links and accessibility'},
  footerNavigation: {default:'Contact and information',title:'Footer navigation description',max:80,group:'Links and accessibility'},
  privacyDescription: {default:'How the Ruslitiki website and waitlist use information you choose to share.',title:'Search description',max:200,group:'Privacy page'},
  privacyBack: {default:'← Ruslitiki',title:'Return link',max:80,group:'Privacy page'},
  privacyIntroduction: {default:'This website introduces Ruslitiki and links to our waitlist. It does not have a signup form of its own or site analytics.',title:'Introduction',max:1200,group:'Privacy page'},
  privacyWaitlistHeading: {default:'The waitlist',title:'Waitlist heading',max:150,group:'Privacy page'},
  privacyWaitlistBody: {default:'The waitlist opens in Google Forms. The form asks for an email address and timezone, with additional questions about reading experience and interests. Olga Ruchina uses this information to plan the club and contact the waitlist when membership opens.',title:'Waitlist information',max:1200,group:'Privacy page'},
  privacyOptionalAnswers: {default:'Please share only what you are comfortable providing. Optional survey answers help shape the reading programme. They are not published as testimonials or shared on this website.',title:'Optional answers',max:1200,group:'Privacy page'},
  privacyGoogleBeforeLink: {default:'Google processes information when you use its form. Read',title:'Before the Google privacy link',max:600,group:'Privacy page'},
  privacyGoogleLink: {default:'Google’s privacy policy',title:'Google privacy link',max:150,group:'Privacy page'},
  privacyGoogleAfterLink: {default:'for details about its service.',title:'After the Google privacy link',max:600,group:'Privacy page'},
  privacyContactHeading: {default:'Questions or removal',title:'Contact heading',max:150,group:'Privacy page'},
  privacyContactBeforeLink: {default:'If you want to ask about your response or request its removal,',title:'Before the contact link',max:600,group:'Privacy page'},
  privacyContactEmail: {default:'contact Olga Ruchina by email',title:'Email contact link',max:150,group:'Privacy page'},
  privacyContactInstagram: {default:'contact Olga Ruchina through the Ruslitiki Instagram account',title:'Instagram contact link',max:150,group:'Privacy page'},
  privacyContactAfterLink: {default:'.',title:'After the contact link',max:600,group:'Privacy page'},
  privacyServicesHeading: {default:'Other services',title:'Other services heading',max:150,group:'Privacy page'},
  privacyYouTubeBeforeLink: {default:'When a YouTube video is available, the website may include a player using YouTube’s privacy-enhanced mode. Loading or playing it connects to YouTube, which processes technical information under',title:'YouTube information before the privacy link',max:1200,group:'Privacy page'},
  privacyYouTubeAfterLink: {default:'. The video does not play automatically.',title:'YouTube information after the privacy link',max:600,group:'Privacy page'},
  privacyHosting: {default:'Our hosting provider processes technical request information to deliver and secure the website. Instagram, Google Forms and, when available, Patreon have their own privacy practices when you visit them.',title:'Hosting and external services',max:1200,group:'Privacy page'},
  notFoundTitle: {default:'Page not found',title:'Browser title',max:100,group:'Page not found'},
  notFoundDescription: {default:'Return to the Ruslitiki book club.',title:'Search description',max:200,group:'Page not found'},
  notFoundHeading: {default:'This page isn’t here.',title:'Heading',max:150,group:'Page not found'},
  notFoundHomeLink: {default:'Return to Ruslitiki',title:'Return link',max:80,group:'Page not found'},
});

export const DEFAULT_LABELS = Object.freeze(Object.fromEntries(Object.entries(LABEL_FIELDS).map(([key,field])=>[key,field.default])));

// Reading an older or partial label map never changes the saved content.
export function labelsFor(content={}) {
  return {...DEFAULT_LABELS,...content.labels};
}
